api = "0.4"

[buildpack]
  id = "paketo-community/cargo-install"
  name = "Rust Cargo Build Pack"
  version = "0.0.3"
  homepage = "https://github.com/paketo-community/cargo-install"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
